exports.SYMBOL_TO_TOKEN_PAIR = {
  'SWAP.LTC': 'SWAP.HIVE:SWAP.LTC',
  'SWAP.BTC': 'SWAP.HIVE:SWAP.BTC',
  'SWAP.ETH': 'SWAP.HIVE:SWAP.ETH',
  'SWAP.HBD': 'SWAP.HIVE:SWAP.HBD',
};

exports.SYMBOLS_FOR_POOL_RATES = ['SWAP.HIVE', ...Object.keys(this.SYMBOL_TO_TOKEN_PAIR)];
